<a href="https://colab.research.google.com/github/anish13-mellam/DAV_Assignment-_193/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()


Saving deepseek_vs_chatgpt.csv to deepseek_vs_chatgpt.csv


In [7]:
import pandas as pd

df = pd.read_csv('deepseek_vs_chatgpt.csv')  # Use the correct file name
df.head()  # Optional: preview the data


Date  Month_Num   Weekday AI_Platform   AI_Model_Version  \
0  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
1  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
2  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
3  2024-09-21          9  Saturday     ChatGPT        GPT-4-turbo   
4  2024-05-16          5  Thursday    DeepSeek  DeepSeek-Chat 1.5   

   Active_Users  New_Users  Churned_Users  Daily_Churn_Rate  Retention_Rate  \
0        500000      25000          25000              0.05            0.95   
1        500000      25000          25000              0.05            0.95   
2        500000      25000          25000              0.05            0.95   
3        500000      25000          25000              0.05            0.95   
4       1700000     170000          34000              0.02            0.95   

   ... Session_Duration_sec     Device_Type Language  Response_Accuracy  \
0  ...                   40          Mobile       es             0.7842   
1  ...                   24  Laptop/Desktop       zh             0.8194   
2  ...                   34          Mobile       en             0.8090   
3  ...                   18          Mobile       fr             0.8233   
4  ...                   10          Mobile       de             0.9366   

   Response_Speed_sec Response_Time_Category  Correction_Needed  \
0                3.30               Standard                  0   
1                3.28               Standard                  1   
2                3.07               Standard                  0   
3                3.06               Standard                  0   
4                1.48                   Fast                  0   

   User_Return_Frequency  Customer_Support_Interactions  \
0                      6                              2   
1                      2                              2   
2                      2                              0   
3                      9                              0   
4                      9                              3   

                                         Region  
0  Antarctica (the territory South of 60 deg S)  
1                                       Ukraine  
2                                       Grenada  
3                                        Guyana  
4                                         India  

[5 rows x 28 columns]

In [8]:
#Importing NumPy and Creating Arrays
import numpy as np
users = df['Active_Users'].values
ratings = df['User_Rating'].values
durations = df['Session_Duration_sec'].values

In [ ]:
# Fixed Type Arrays & Data Types
users.dtype  # dtype('int64')
ratings.dtype  # dtype('int64')

dtype('int64')

In [9]:
 #Array Indexing and Slicing
print(users[0])        # First user count
print(users[0:5])      # First 5 user counts
print(users[-1])       # Last entry

500000
[ 500000  500000  500000  500000 1700000]
1700000


In [10]:
 #Reshaping Arrays
reshaped = users[:10].reshape(2, 5)  # 2 rows, 5 cols
print("Reshaped array (2x5):\n", reshaped)

Reshaped array (2x5):
 [[ 500000  500000  500000  500000 1700000]
 [1700000 1700000 1700000 1700000 1700000]]


In [11]:
 #Concatenation and Splitting
combined = np.concatenate([users[:5], users[-5:]])
print("Concatenated array:", combined)

split1, split2 = np.split(users[:10], 2)
print("First split:", split1)
print("Second split:", split2)

Concatenated array: [ 500000  500000  500000  500000 1700000 1700000 1700000 1700000 1700000
 1700000]
First split: [ 500000  500000  500000  500000 1700000]
Second split: [1700000 1700000 1700000 1700000 1700000]


In [12]:
#Universal Functions
print("Square root of first 5 ratings:", np.sqrt(ratings[:5]))
print("Log of first 5 user counts:", np.log1p(users[:5]))
print("Exponential of first 5 durations:", np.exp(durations[:5]))

Square root of first 5 ratings: [2.         2.         1.73205081 2.23606798 2.23606798]
Log of first 5 user counts: [13.12236538 13.12236538 13.12236538 13.12236538 14.3461394 ]
Exponential of first 5 durations: [2.35385267e+17 2.64891221e+10 5.83461743e+14 6.56599691e+07
 2.20264658e+04]


In [13]:
#Aggregations
print("Average rating:", np.mean(ratings))
print("Total active users:", np.sum(users))
print("Maximum session duration:", np.max(durations))
print("Median session duration:", np.median(durations))

Average rating: 4.3947
Total active users: 11962550000
Maximum session duration: 60
Median session duration: 27.0


In [14]:
#Broadcasting Rules
normalized = durations / np.max(durations)
print("Normalized durations:", normalized[:5])

Normalized durations: [0.66666667 0.4        0.56666667 0.3        0.16666667]


In [15]:
#Comparisons and Boolean Arrays
high_rating = ratings > 4
long_sessions = durations > 60
print("High ratings (>4):", high_rating[:5])
print("Long sessions (>60 sec):", long_sessions[:5])

High ratings (>4): [False False False  True  True]
Long sessions (>60 sec): [False False False False False]


In [16]:
#Masks and Fancy Indexing
high_rating_users = users[ratings > 4]
long_sessions_values = durations[durations > 60]
print("Users with high ratings:", high_rating_users[:5])
print("Durations > 60 sec:", long_sessions_values[:5])

Users with high ratings: [ 500000 1700000 1700000 1700000 1700000]
Durations > 60 sec: []


In [17]:
#Fast Sorting with np.sort and np.argsort
sorted_ratings = np.sort(ratings)
print("Sorted ratings:", sorted_ratings[:10])

top_duration_indices = np.argsort(durations)[-5:]
print("Top 5 longest session durations:", durations[top_duration_indices])

Sorted ratings: [3 3 3 3 3 3 3 3 3 3]
Top 5 longest session durations: [60 60 60 60 60]


In [19]:
 #Partial Sorting with np.partition
top5_fast = np.partition(durations, -5)[-5:]
print("Top 5 durations using partition:", top5_fast)

Top 5 durations using partition: [60 60 60 60 60]


In [18]:
import pandas as pd
import numpy as np

# Load CSV file
df = pd.read_csv('/content/deepseek_vs_chatgpt.csv')

# Extract columns as NumPy arrays
users = np.array(df['Active_Users'], dtype=np.int32)
ratings = np.array(df['User_Rating'], dtype=np.int32)
durations = np.array(df['Session_Duration_sec'], dtype=np.int32)

In [20]:
#Partial Sorting
top5_fast = np.partition(durations, -5)[-5:]
print("Top 5 session durations (unsorted):", top5_fast)

Top 5 session durations (unsorted): [60 60 60 60 60]


In [21]:
#Cumulative Sum
cumulative = np.cumsum(users[:5])
print("Cumulative user count:", cumulative)

Cumulative user count: [ 500000 1000000 1500000 2000000 3700000]
